config/routes.rb
Rails.application.routes.draw do
  resources :drafts
  get 'static_pages/about'

  root 'static_pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/draft.rb
class Draft < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  before_action :set_draft, only: [:show, :edit, :update, :destroy]

  # GET /drafts
  # GET /drafts.json
  def index
    @drafts = Draft.all
  end

  # GET /drafts/1
  # GET /drafts/1.json
  def show
  end

  # GET /drafts/new
  def new
    @draft = Draft.new
  end

  # GET /drafts/1/edit
  def edit
  end

  # POST /drafts
  # POST /drafts.json
  def create
    @draft = Draft.new(draft_params)

    respond_to do |format|
      if @draft.save
        format.html { redirect_to @draft, notice: 'Draft was successfully created.' }
        format.json { render :show, status: :created, location: @draft }
      else
        format.html { render :new }
        format.json { render json: @draft.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drafts/1
  # PATCH/PUT /drafts/1.json
  def update
    respond_to do |format|
      if @draft.update(draft_params)
        format.html { redirect_to @draft, notice: 'Draft was successfully updated.' }
        format.json { render :show, status: :ok, location: @draft }
      else
        format.html { render :edit }
        format.json { render json: @draft.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drafts/1
  # DELETE /drafts/1.json
  def destroy
    @draft.destroy
    respond_to do |format|
      format.html { redirect_to drafts_url, notice: 'Draft was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_draft
      @draft = Draft.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def draft_params
      params.require(:draft).permit(:title, :body, :image_url)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/drafts/_form.html.erb
<%= form_for(draft) do |f| %>
  <% if draft.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(draft.errors.count, "error") %> prohibited this draft from being saved:</h2>

      <ul>
      <% draft.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drafts/edit.html.erb
<h1>Editing Draft</h1>

<%= render 'form', draft: @draft %>

<%= link_to 'Show', @draft %> |
<%= link_to 'Back', drafts_path %>

app/views/drafts/index.html.erb
<div id="drafts" class="container-page">
  <p id="notice"><%= notice %></p>
  <div class="row">
    <div id="left-sidebar" class="col-md-4">
      <h3 class="center">See drafts in other languages</h3>
      <div class="sidebar-nav-fixed">         
        <div class="well">
          <h4><i class="fa fa-comments-o"></i>  ...  become fluent in your second language by expressing yourself.</h4>
        </div>
        <!--/.well -->
        <div class="well">
          <h4><i class="fa fa-leanpub"></i>  ...  learn from feedback by native and fluent speakers.</h4>
        </div>
        <!--/.well -->
        <div class="well">
          <h4><i class="fa fa-question-circle-o"></i>  ...  help other learners to become fluent in your native or dominant language.</h4>
        </div>
        <!--/.well -->
        <div class="well">
          <h4><i class="fa fa-bullhorn"></i>  ...  react to posts and follow people wishing to freely express themselves just like they would do on facebook or twitter.</h4>
        </div>
        <!--/.well -->
      </div>
      <!--/.sidebar nav fixed -->
    </div>
    <!--/#left sidebar -->
    <div id="main-content" class="col-md-8">
      <h1>Drafts</h1>
      <article>
        <% @drafts.each do |draft| %>
          <%= image_tag(draft.image_url, class: "img-responsive") %>
          
          <h2><%= draft.title %></h2>
          <p><%= draft.body %></p>
          

          <span><%= link_to 'Show', draft %> | <%= link_to 'Edit', edit_draft_path(draft) %> | <%= link_to 'Destroy', draft, method: :delete, data: { confirm: 'Are you sure?' } %>
        </span>
      <% end %>
     </article>
    <%= link_to 'New Draft', new_draft_path %>
    </div>
    <!--/#main-content -->
  </div>
  <!--/.row -->
</div>
<!--/#drafts -->

app/views/drafts/new.html.erb
<h1>New Draft</h1>

<%= render 'form', draft: @draft %>

<%= link_to 'Back', drafts_path %>

app/views/drafts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @draft.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @draft.body %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @draft.image_url %>
</p>

<%= link_to 'Edit', edit_draft_path(@draft) %> |
<%= link_to 'Back', drafts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Babellog</title>
    <!-- link to Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <!--/link to bootstrap -->

    <!-- font awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <!--/font awesome -->

    <!-- link to Google fonts -->
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <!--/link to Google fonts -->

    <!-- link to javascript -->
    <%= javascript_include_tag 'application' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!--/link to javascript -->

    <!--favicon -->
    <%= favicon_link_tag 'favicon.ico' %>
    <!--/favicon -->

    <!-- responsive for viewports -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--/responsive for viewports -->
    <%= csrf_meta_tags %>
    <!-- turbolinks -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--/turbolinks -->
  </head>
  <body>
    <div id="wrap">
      <!-- ==================== -->
      <!-- Navigation comes now -->
      <!-- ==================== -->
      <!-- Collect the nav links, forms, and other content for toggling -->
      <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand brand page-scroll" href="#page-top"><span class="logo">Babellog</span>
            </a> 
          </div> 
          <!-- /.nav-header -->

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li>
                <a href="#">Home</a>
              </li>
              <li>
                <a href="#">Blog</a>
              </li>
              <li>
                <a href="#">CEFR levels</a>
              </li>
              <li>
                <a href="#">About</a>
              </li>
              <li>
                <a href="#">Sign up</a>
              </li>
              <li>
                <a href="#">Login</a>
              </li>
            </ul>
          </div>
          <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
      </nav>
      <!-- /.navbar -->
      <!-- /////////////// -->
      <!-- Navigation ends -->
      <!-- /////////////// -->

      <!-- alerts and notices -->

      <!--/.alerts and notices -->
      <div id="main-container-site" class="container">
        <div class="row">
          <div id="central-content" class="col-md-10">
            <%= yield %>
          </div>
          <!--/#central-content -->
          <div id="right-sidebar" class="col-md-2">
            <div class="sidebar-nav-fixed">
              <div id="networking" class="center">
                <a href="#"><i class="fa fa-facebook-square"></i></a>
                <a href="#"><i class="fa fa-twitter-square"></i></a>
                <a href="#"><i class="fa fa-google-plus-square"></i></a>
                <a href="#"><i class="fa fa-linkedin-square"></i></a>
                <a href="#"><i class="fa fa-tumblr-square"></i></a>
                <a href="#"><i class="fa fa-delicious"></i></a>
              </div>
              <!--/#networking -->
              <div class="well article-search">
                <ul class="nav">
                  <li class="nav-header">Search Articles</li>
                  <li><a href="#">CEFR level</a></li>
                  <li><a href="#">Language</a></li>
                  <li><a href="#">Topic</a></li>
                  <li><a href="#">Type of article</a></li>
                  <li><a href="#" class="btn btn-default">Search</a></li>
                </ul> 
              </div>
              <!--/.well article-search -->
            </div>
            <!--/.sidebar-nav-fixed -->
          </div>
          <!--#right-sidebar -->
        </div>
        <!--/.row -->
      </div>
      <!--/.container -->
    </div>
    <!--/#wrap -->
    <footer>
      <div class="container copyright">
        &copy; 2016 Babellog
      </div>
    </footer>
  </body>
</html>

app/views/static_pages/about.html.erb
<div id="about" class="container-page">
	<div class="row">
		<div id="left-sidebar" class="col-md-4">
			<div class="sidebar-nav-fixed">					<div class="well">
					<p>hello World</p>	
				</div>
				<!--/.well -->
			</div>
			<!--/.sidebar nav fixed -->
		</div>
		<!--/#left sidebar -->
		<div id="main-content" class="col-md-8">
			<h1>About Babellog</h1>
			<p>Become fluent in your second language by expressing yourself.</p>
			<p>Learn from feedback by native and fluent speakers</p>
			<p>Help other learners to become fluent in your native or dominant language</p>
			<p>React to posts and follow people wishing to freely express themselves just like they would do on facebook or twitter</p>
		</div>
		<!--/#main-content -->
	</div>
	<!--/.row -->
</div>
<!--/#about -->

app/views/static_pages/index.html.erb
<div id="home" class="container-page">
	<div class="row">
		<div id="left-sidebar" class="col-md-4">
			<h3 class="center">Babellog aims to help you</h3>
			<div class="sidebar-nav-fixed">					
				<div class="well">
					<h4><i class="fa fa-comments-o"></i>  ...  become fluent in your second language by expressing yourself.</h4>
				</div>
				<!--/.well -->
				<div class="well">
					<h4><i class="fa fa-leanpub"></i>  ...  learn from feedback by native and fluent speakers.</h4>
				</div>
				<!--/.well -->
				<div class="well">
					<h4><i class="fa fa-question-circle-o"></i>  ...  help other learners to become fluent in your native or dominant language.</h4>
				</div>
				<!--/.well -->
				<div class="well">
					<h4><i class="fa fa-bullhorn"></i>  ...  react to posts and follow people wishing to freely express themselves just like they would do on facebook or twitter.</h4>
				</div>
				<!--/.well -->
			</div>
			<!--/.sidebar nav fixed -->
		</div>
		<!--/#left sidebar -->
		<div id="main-content" class="col-md-8">
			<h1>Last published articles</h1>
			
		</div>
		<!--/#main-content -->
	</div>
	<!--/.row -->
</div>
<!--/#home -->